Repository srebrasil/srebrasil.github.io, pull requests merged in 2022-06, with the labels that each got.

#179 Revisar | https://thenewstack.io/can-sre-bring-governance-and-compliance-into-the-future/
  _posts/2022-06-05-can-sre-bring-governance-and-compliance-into-the-future.markdown
Labels: Artigo comentado

#180 Revisar | https://thenewstack.io/the-need-to-decouple-human-error-from-incident-response/
  _posts/2022-06-05-the-need-to-decouple-human-error-from-incident-response.markdown
Labels: Artigo comentado

#181 Preparar Index da Edição 13
  anteriores.md
  assets/SRE Brasil Notícias 12.png
  index.markdown
Labels: documentation

#195 testar yaml lint
  _posts/2022-06-09-dummy2.markdown
Labels: good first issue

#198 why-you-need-chaos-engineering
  .gitignore
  _posts/2022-06-13-readiness-to-learn-safely-and-reliably-deploy-to-the-cloud.markdown
  _posts/2022-06-13-the-cyber-incident-response-plan-the-power-is-in-the-process.markdown
  _posts/2022-06-13-why-you-need-chaos-engineering.markdown
Labels: Artigo comentado

#207 PR dos artigos da edição 15
  _posts/2022-06-18-incident-response-incident-priority-matrix copy.markdown
  _posts/2022-06-18-starting-an-sre-team-from-scratch-quick-guide.markdown
  _posts/2022-06-18-what-is-an-sre-product-manager copy.markdown
Labels: Artigo comentado

#220 Atualização do Docker-compose
  docker-compose.yml
Labels: enhancement

#222 teste new docker build
  Deployment.yaml
Labels: enhancement
